module.exports = {
    askContinue0: '¡Eh! ¿Sigues por ahí? La bonilista que has pedido aún no ha terminado pero necesitaba parar unos segundos y tomar aire, ¿quieres que continúe con la bonilista?',
    askContinue1: '¿Sigues ahí? La bonilista que quieres escuchar es un poco más larga de lo que pensaba y necesitaba descansar un poco, pero ya estoy lista para la siguiente parte, ¿quieres seguir escuchándola?',
    askContinue2: 'Aún queda un poco más de bonilista, ¿quieres seguir escuchando más?',
    askContinue3: 'Es mucha información, lo sé, por eso he parado un poco, para que puedas asimilarla mejor, ¿quieres que siga?',
    askContinue4: '¿Estás por ahí? Esto aún no ha acabado, queda un poco más de historia, ¿quieres que sigamos?',
    byeText: 'Vale! Te esperamos la semana que viene con otra entrega de la bonilista.',
    endBonilista: 'Hasta aquí la bonilista, si te apetece puedes pedirme que te lea otra entrega.',
    error: 'Ups! Vaya! La hemos liado un poco y ahora no te podemos ofrecer las últimas noticias, lo estamos arreglando, pregúntame dentro de un rato a ver si ya hemos encotrado el problema.',
    errorText: 'Perdona, creo que estaba un poco despistada y no te he entendido, puedes repetirlo otra vez?',
    helpText: 'Recuerda que puedes pedirme las bonilistas de las últimas 10 semanas, por ejemplo, Leeme la última bonilista. O, leeme la bonilista de hace 2 semanas. Si no sabes cual es la que te interesa, me puedes pedir los títulos de las bonilistas disponibles.', 
    helpTextCard: 'Recuerda que puedes pedirme las bonilistas de las últimas 10 semanas, por ejemplo Leeme la última bonilista, o la bonilista de hace 2 semanas. Si no sabes cual es la que te interesa, me puedes pedir los títulos de las bonilistas disponibles.', 
    helpTenWeeksAgo: 'Recuerda que puedes pedirme las bonilistas de las últimas 10 semanas, es decir de la semana actual hasta hace 9 semanas...',
    longPause: '<break time="2s" />',
    of: 'de',
    pause: '<break time="1.5s" />',
    sectionReprompt: 'Puedes pedirme las bonilistas de las últimas 10 semanas, por ejemplo Leeme la última bonilista, o la bonilista de hace 2 semanas.',
    shortPause: '<break time="1s" />',
    title: 'La bonilista',
    titles: 'Aquí tienes los últimos títulos:',
    titleThisWeek: 'Esta semana tenemos.',
    titleLastWeek: 'Hace una semana tuvimos.',
    titleNWweeks: 'Hace {n} semanas tuvimos.',
    titlesEnd: '¿Cúal quieres escuchar?',
    welcomeText: 'Te damos la bienvenida a la Bonilista; ¡Camarada del metal!. Me puedes pedir que te lea las bonilistas de las últimas 10 semanas; puedes decir, leeme la bonilista de hace 3 semanas. O, leeme la bonilista de la última semana. Si no sabes cual es la que te interesa, te puedo decir también los títulos de las bonilistas disponibles. ¿Qué prefieres?',
    welcomeTextCard: 'Te damos la bienvenida a la Bonilista; ¡Camarada del metal!. Me puedes pedir que te lea las bonilistas de las últimas 10 semanas; puedes decir, leeme la bonilista de hace 3 semanas, o leeme la bonilista de la última semana. Si no sabes cual es la que te interesa, te puedo decir también los títulos de las bonilistas disponibles. ¿Qué prefieres?'
}